title: "           <black>Auto Kill Settings"
rows: 6
pageable-slot-size: 28
filler-material: "GRAY_STAINED_GLASS_PANE"
filler-slots:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 17
  - 18
  - 26
  - 27
  - 35
  - 36
  - 44
  - 45
  - 46
  - 47
  - 48
  - 50
  - 51
  - 52
  - 53

entity:
  enabled:
    material: STONE # keep this here
    model-data: 0
    amount: 1
    display-name: "<entity>"
    glowing: false
    head-data: null
    lore:
      - ""
      - "<#5b9397>Entity Settings ↓"
      - "<gray>Is killed automatically: <green>Yes"
      - ""
      - "<yellow><italic>Click to toggle"
    slots: []
    actions:
      - "[sound] ENTITY_ITEM_PICKUP"
  disabled:
    material: STONE # keep this here
    model-data: 0
    amount: 1
    display-name: "<entity>"
    glowing: false
    head-data: null
    lore:
      - ""
      - "<#5b9397>Entity Settings ↓"
      - "<gray>Is killed automatically: <red>No"
      - ""
      - "<yellow><italic>Click to toggle"
    slots: [ ]
    actions:
      - "[sound] ENTITY_ITEM_PICKUP"

items:
  module_settings:
    material: "OAK_HANGING_SIGN"
    model-data: 0
    amount: 1
    display-name: "<#ff0000>Which Entities You Want to Kill?"
    glowing: false
    head-data: null
    lore:
      - ""
      - " <gray>Click items below to toggle"
      - " <gray>whether you want those entities"
      - " <gray>to get killed automatically!"
      - ""
    slots:
      - 4
    actions: []
  back:
    material: "BARRIER"
    model-data: 0
    amount: 1
    display-name: "<#ff0000>Go Back"
    glowing: false
    head-data: null
    lore:
      - ""
    slots:
      - 49
    actions:
      - "[menu] settings"