# check https://jd.papermc.io/paper/org/bukkit/Sound.html for whenever you need help with sounds

config-version: "${version}" # do not change this
language: en # supported languages: TR, EN
license-key: ""

hooks:
  # Region Hook
  # supported plugins:
  #  - uxmClaims - recommended claim plugin
  #  - IridiumSkyblock
  #  - SuperiorSkyblock2
  #  - BentoBox:BSkyBlock usage: BentoBox:<island world friendly name from your addon config>
  #  - BentoBox:OneBlock usage: BentoBox:<island world friendly name from your addon config>
  #  - Lands
  #  - RealmCore
  #  - GriefPrevention
  #  - GriefDefender - does not support place-farmer-on-region-creation
  # -  ProtectionStones usage: ProtectionStones:<claim world's name>, supports place-farmer-on-region-creation but best to keep it disabled
  #  - RClaim
  #  - Towny (for TownyAdvanced)
  #  - UltimateClaims
  #  - FabledSkyBlock
  #  - DeluxeSkyblock
  region-hook: "uxmClaims"

  # Economy Hook
  # supported plugins:
  #  - Vault
  #  - PlayerPoints
  #  - SuperiorSkyblock2 - uses island bank
  money-hook: "Vault"

  # Price Source Hook
  # supported plugins
  #  - ShopGUIPlus
  #  - EconomyShopGUI or EconomyShopGUI-Premium
  #  - ExcellentShop
  #  - default or "" - prices from collected-materials.yml
  price-source-hook: default

  # Interaction Hook
  # supported plugins:
  # - Holograms - this is internal, plugin uses it for everywhere you see holograms.
  # - Citizens
  # - FancyNpcs
  # - ZNPCsPlus
  # - ModelSystem (ModelEngine, ItemsAdder or BetterModel) - this is internal, can be configured in model-settings
  # - default or "" - no interaction, farmer only accessible by commands
  interaction-hook: "FancyNpcs"

database:
  #MYSQL, SQLITE
  driver: "SQLITE"
  host: "localhost"
  database: "database"
  username: ""
  password: ""
  port: 3306
  use-ssl: false

multi-server:
  # enable this option if you are using more than one server
  enabled: false
  redis-host: ""

model-settings:
  default-entity: VILLAGER
  # can be ModelEngine, ItemsAdder or BetterModel
  model-source: ModelEngine
  model-name: "test"

world-management:
  world-list:
    - "world"
  # can be BLACKLIST or WHITELIST
  # BLACKLIST = worlds that farmer must not be usable
  # WHITELIST = worlds that farmer must be usable
  list-type: BLACKLIST

log-cleaner:
  # if you have been using the plugin for a long time and players have a lot of logs
  # log cleaner may cause lag at first usages in rare cases.
  # in case that happens, disable log cleaner and clear your database table of logs
  # if you are not able to do it, open a ticket in UXPLIMA discord server
  enabled: true
  # configured like below, log cleaner will remove oldest 25 logs after 50 created logs.
  clean-old-logs-after: 50
  logs-to-clean: 25

# cooldowns are in seconds
cooldowns:
  move-cooldown: 180
  sell-all-cooldown: 120
  sell-xp-cooldown: 120
  change-glowing-cooldown: 120
  change-entity-cooldown: 120
  change-profession-cooldown: 120
  return-cooldown: 120

sounds:
  on-cooldown: BLOCK_ANVIL_LAND
  try-again: BLOCK_NOTE_BLOCK_PLING
  already-using-that-glow-color: UI_BUTTON_CLICK
  blacklisted-world: BLOCK_ANVIL_BREAK

# never open this unless UXPLIMA staff told you to do
debug: false
# categories are NONE, ALL, AUTO_KILL, AUTO_SELL, AUTO_HARVEST, XP_COLLECTOR, HANDLE_ITEM, GENERAL
debug-categories:
- NONE
ignore: []