title: "           <black>Auto Sell Settings"
rows: 6
pageable-slot-size: 28
filler-material: "GRAY_STAINED_GLASS_PANE"
filler-slots:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 17
  - 18
  - 26
  - 27
  - 35
  - 36
  - 44
  - 45
  - 46
  - 47
  - 48
  - 50
  - 51
  - 52
  - 53

material:
  enabled:
    material: STONE # keep this here
    model-data: 0
    amount: 1
    display-name: "<material>"
    glowing: false
    head-data: null
    lore:
      - ""
      - "<#5b9397>Eşya Ayarları ↓"
      - "<gray>Otomatik olarak satılıyor: <green>Evet"
      - ""
      - "<yellow><italic>Değiştirmek için tıkla"
    slots: []
    actions:
      - "[sound] ENTITY_ITEM_PICKUP"
  disabled:
    material: STONE # keep this here
    model-data: 0
    amount: 1
    display-name: "<material>"
    glowing: false
    head-data: null
    lore:
      - ""
      - "<#5b9397>Eşya Ayarları ↓"
      - "<gray>Otomatik olarak satılıyor: <red>Hayır"
      - ""
      - "<yellow><italic>Değiştirmek için tıkla"
    slots: [ ]
    actions:
      - "[sound] ENTITY_ITEM_PICKUP"

items:
  module_settings:
    material: "OAK_HANGING_SIGN"
    model-data: 0
    amount: 1
    display-name: "<#ff0000>Hangi Eşyaları Satmak İstiyorsun?"
    glowing: false
    head-data: null
    lore:
      - ""
      - " <gray>Aşağıdaki butonları kullanarak"
      - " <gray>o eşyaların otomatik olarak"
      - " <gray>satılmasını ayarlayabilirsin."
      - ""
    slots:
      - 4
    actions: []
  back:
    material: "BARRIER"
    model-data: 0
    amount: 1
    display-name: "<#ff0000>Geri Git"
    glowing: false
    head-data: null
    lore:
      - ""
    slots:
      - 49
    actions:
      - "[menu] settings"